CREATE TABLE users
(
    id            INT(16) AUTO_INCREMENT PRIMARY KEY,
    `name`        VARCHAR(50) NOT NULL,
    email         VARCHAR(50) NOT NULL,
    mobile_number VARCHAR(50) NOT NULL,
    password      VARCHAR(50) NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP
);
